### ISSUE TITLE
NPE when CAS server doesn't return attributes on validation

### ISSUE THREAD

**Issue by hunarletsko** [johnjcool/keycloak-cas-services#21]
As according to documentation https://apereo.github.io/cas/4.2.x/protocol/CAS-Protocol-Specification.html#appendix-a-cas-response-xml-schema attributes are nullable it can be issue when CAS server doesn't provide attributes and it is reason of NPE at org.keycloak.authentication.authenticators.broker.util.SerializedBrokeredIdentityContext.serialize(SerializedBrokeredIdentityContext.java:310)
I have fix of that. Could you please add me as contributor to this project to make pull request for this fix

**Comment by hunarletsko** [comment]
when I''m trying to push my branch I got : Permission to johnjcool/keycloak-cas-services.git denied to hunarletsko.
fatal: unable to access 'https://github.com/johnjcool/keycloak-cas-services.git/': The requested URL returned error: 403

**Comment by udanieli** [comment]
@hunarletsko push the branch on your fork, I would like to take a look and test your fix too. Thank you
