### ISSUE TITLE
Creating new CAS Service broken

### ISSUE THREAD

**Issue by ataraxus** [johnjcool/keycloak-cas-services#3]
If one wants to create a new CAS IDP it fails, since the creation template is not available under: 

`http://localhost:8086/auth/resources/4.1.0.final/admin/`**keycloak**`/partials/realm-identity-provider-saml.html`

as expected by keycloak, but under: 

`http://localhost:8086/auth/resources/4.1.0.final/admin/`**keycloak-extended**`/partials/realm-identity-provider-saml.html`

**Comment by johnjcool** [comment]
you have to activate the keycloak-extended theme as admin theme under master realm.

**Comment by ataraxus** [comment]
thats a good point! but it didn't changed anything. i switched the admin theme in the master and in the user realm to 'keycloak-extended' but still the template ist only available 

`http://localhost:8086/auth/resources/4.1.0.final/admin/keycloak-extended/partials/realm-identity-provider-cas.html`

**Comment by ataraxus** [comment]
Okay, problem solved! It seems this is not hot deployment save... after restarting it works expected (after applying the pull request). 
Thanks!
